language: python
python:
  - "2.7"
  - "3.6"
env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.2
install:
  - pip install -q Django==$DJANGO_VERSION --use-mirrors
  - pip install -q -r requirements.txt --use-mirrors
script: python manage.py test
